name: Checkout
on: [push]
jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: 파일목록 보기1
        run: ls -a
      - name: 소스다운로드
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: 파일목록 보기2
        run: ls -a
