name: External Event
on:
    repository_dispatch:
        types: [build]
jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Repository Dispatch Event Received"
            - run: echo ${{ github.event.client_payload.env }}