name: Manual Trigger Workflow2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment' 
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Show input
        run: echo "Selected environment: ${{ github.event.inputs.environment }}"