name: Pull Request Comment
on:
  pull_request_target:
    types: [opened]
permissions:
  issues: write
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on New PRs
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['needs review']
            });
