name: Workflow Commands1
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting an error message with params
        run: echo "::error title=Error2,file=app.js,line=2,endLine=3::Missing Semicolon"
      - name: Setting a debug message with params
        run: echo "::debug title=Debug,file=app.js,line=2,endLine=3::Missing Semicolon"
      - name: Setting an warning message with params
        run: echo "::warning title=Warnin ,file=app.js,line=2,endLine=3::Missing Semicolon"
      - name: Setting an notice message with params
        run: echo "::notice title=Notice ,file=app.js,line=2,endLine=3::Missing Semicolon"
      - name: Group of logs
        run: |
          echo "::group::My group title"
          echo "Inside group"
          echo "Inside group 2"
          echo "Inside group 3"
          echo "::endgroup::"